# Development configuration - use with: docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build
services:
  app:
    # Use local build instead of GHCR image
    image: track-finance:local-dev
    build: .
    # Mount source code for live reloading
    volumes:
      - .:/app
    # Use Flask development server
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000 --debug"
    # Development environment
    environment:
      FLASK_ENV: development
