# This file is for local development and overrides the main docker-compose.yml
services:
  app:
    # In local development, build the image from the Dockerfile
    # instead of pulling it from the registry.
    build: .
    # Mount the current directory into the container for live code reloading.
    volumes:
      - .:/app
    # Use Flask's built-in development server with auto-reloading.
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    environment:
      - FLASK_ENV=development
