services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: track_finance_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: track_finance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432" # Local access with pgAdmin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U track_finance_user -d track_finance"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/zekeriyaay/track-finance:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://track_finance_user:${POSTGRES_PASSWORD:-change_me}@db:5432/track_finance"
      SECRET_KEY: ${SECRET_KEY:-very-secret-key}
      FLASK_APP: "app.py"
    ports:
      - "5001:5000"
    command: >
      sh -c "flask db upgrade && gunicorn -c gunicorn-conf.py app:app"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_SETUP_SERVERS: "/pgadmin4/servers.json"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
