# This file is for local development and overrides the main docker-compose.yml
services:
  app:
    # Override the image directive - use local build instead of GHCR
    image: track-finance:local-dev
    build: .
    # Mount source code for live reloading
    volumes:
      - .:/app
    # Use Flask development server instead of Gunicorn
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000 --debug"
    # Add development-specific environment variables
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
