apiVersion: 1

datasources:
  - name: Track Finance PostgreSQL
    type: postgres
    uid: postgres
    access: proxy
    url: db:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500  # PostgreSQL 15
      timescaledb: false
    isDefault: true
    editable: true
