"""add bank sync support

Revision ID: 31087fde7665
Revises: add_user_auth
Create Date: 2026-02-09 20:59:28.922982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31087fde7665'
down_revision = 'add_user_auth'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_code', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('client_id_encrypted', sa.Text(), nullable=True),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashflow_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_transaction_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_connection_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cashflow_transaction_external_transaction_id'), ['external_transaction_id'], unique=False)
        batch_op.create_unique_constraint('uq_external_txn_bank', ['external_transaction_id', 'bank_connection_id'])
        batch_op.create_foreign_key(None, 'bank_connection', ['bank_connection_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashflow_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_external_txn_bank', type_='unique')
        batch_op.drop_index(batch_op.f('ix_cashflow_transaction_external_transaction_id'))
        batch_op.drop_column('bank_connection_id')
        batch_op.drop_column('source')
        batch_op.drop_column('external_transaction_id')

    op.drop_table('bank_connection')
    # ### end Alembic commands ###
